service: vigil
image: byronfichardt/vigil

servers:
  web:
    hosts:
      - 204.168.132.32
    cmd: /entrypoint.sh
    options:
      volume: /data/vigil/database:/var/www/html/database

proxy:
  ssl: true
  host: vigil.byronfichardt.com
  app_port: 80
  healthcheck:
    path: /up
    interval: 3
    timeout: 120
  run:
    metrics_port: 1318

registry:
  server: ghcr.io
  username: byronfichardt
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    APP_NAME: "Vigil"
    APP_ENV: production
    APP_DEBUG: "false"
    APP_URL: https://vigil.byronfichardt.com
    LOG_CHANNEL: stack
    LOG_LEVEL: error
    DB_CONNECTION: sqlite
    SESSION_DRIVER: database
    QUEUE_CONNECTION: database
    CACHE_STORE: database
  secret:
    - APP_KEY
